[tool.ruff]
line-length = 100
target-version = "py39"
select = [
	"A",
	"C4",
	"E",
	"F",
	"I",
	"PIE",
	"PTH",
	"Q",
	"RET",
	"RSE",
	"RUF",
	"TCH",
	"TD003",
	"TID",
	"W",
]
task-tags = ["TODO", "FIXME", "XXX", "HACK"]

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]
force-single-line = true
lines-after-imports = 2
lines-between-types = 1
