[tool.ruff]
line-length = 100
target-version = "py39"
select = [
	"A",
	"C4",
	"E",
	"F",
	"I",
	"PIE",
	"PTH",
	"RET",
	"RSE",
	"RUF",
	"TCH",
	"TD003",
	"TID",
	"W",
]
ignore = ["E111", "E114", "E117", "E501", "W191"]
task-tags = ["TODO", "FIXME", "XXX", "HACK"]
fix = true

[tool.ruff.isort]
required-imports = ["from __future__ import annotations"]
force-single-line = true
